# Holds API credentials / session-scoped objects.

from growwapi import GrowwAPI

# Put your token here (unchanged behavior)
API_AUTH_TOKEN: str = "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NTQ3ODU4MDAsImlhdCI6MTc1NDczNTUzMCwibmJmIjoxNzU0NzM1NTMwLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCIzNmJkNTQyYi0zYTk4LTQxMGQtOTBhNS04OTU1N2QxMjU0ZDNcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiZjY2OGJhOWEtMTNhOS00YWU0LWEwNTItMTA3NWE0YWI0NzM2XCIsXCJkZXZpY2VJZFwiOlwiMGIxMmIzN2MtMjg0ZS01YTZiLTlhYjUtNDAzNmVmOGFmZmNmXCIsXCJzZXNzaW9uSWRcIjpcImZjYjM1OGRlLTQyYjItNGJjYy04MzgxLTk1MjYzN2U4ZDMxMVwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYlBHeXJkdzdaYTBqNktXeGZ5Nm9wclpSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcIm9yZGVyLWJhc2ljLGxpdmVfZGF0YS1iYXNpYyxub25fdHJhZGluZy1iYXNpYyxvcmRlcl9yZWFkX29ubHktYmFzaWNcIixcInNvdXJjZUlwQWRkcmVzc1wiOlwiMjAwMTo5ZTg6NzFmNDo0YjAwOjI0N2I6MWYzMDoxMWU4OmFjZWQsMTYyLjE1OC45NS4xNzEsMzUuMjQxLjIzLjEyM1wiLFwidHdvRmFFeHBpcnlUc1wiOjE3NTQ3ODU4MDAwMDB9IiwiaXNzIjoiYXBleC1hdXRoLXByb2QtYXBwIn0.PWDjnxqZFFj0pbHq6Vcv19FnTdI4go4-lTzfrFRHkAmhvaFKndwVGf-4zi0hfTbeVRuEfnd_4npUNG4H04aKuw"

# NOTE: GrowwAPI instance is created inside data_pipeline when needed.
# Keeping token centralized here avoids duplicating strings in multiple files.
